[package]
name = "sh4der-jockey"
version = "0.3.1"
description = "A tool for shader coding and live performances"
edition = "2018"
build = "build.rs"

[profile.release]
lto = "fat"

[dependencies]
alloca = { git = "https://github.com/slerpyyy/alloca-rs", branch = "v2" }
anyhow = "1.0"
as-any = "0.3"
async-std = { version = "1.12", default-features = false, features = ["std"] }
clap = { version = "4.5.4", features = ["derive"] }
cpal = "0.15.3"
ctrlc = { version = "3.2", features = ["termination"] }
dirs = "5.0.1"
futures = { version = "0.3", default-features = false }
gl = "0.14"
glutin = "0.26" # must match version used in imgui forks
image = "0.23" # BGR* image formats are removed in later versions
imgui = { git = "https://github.com/sp4ghet/imgui-rs", branch = "master" }
imgui-opengl-renderer = { git = "https://github.com/sp4ghet/rust-imgui-opengl-renderer", branch = "master" }
imgui-winit-support = { git = "https://github.com/sp4ghet/imgui-rs", branch = "master" }
lazy_static = "1.4"
libloading = "0.8"
log = "0.4"
midir = "0.10.0"
ndi = { git = "https://github.com/slerpyyy/ndi-rs", branch = "main" }
notify = "6.1"
num-complex = "0.4"
rand = "0.8"
regex = "1.4"
rfd = "0.14"
rosc = "0.11"
rustfft = "6.0"
serde_yaml = "0.9"
simplelog = "0.12"
take_mut = "0.2"
winapi = { version = "0.3.9", features = ["wincon", "winuser", "handleapi", "synchapi", "memoryapi", "winerror"] }

[build-dependencies]
anyhow = "1.0"
vergen = { version = "8.3.2", features = ["build", "git", "git2"] }
